### ISSUE TITLE
建议增量同步增加自定义字段功能

### ISSUE THREAD

**Issue by JokkerLiu** [datavane/tis#104]
需求描述：
10个Mysql库，每个库中有同一个表名、表结构的表，现需要将这10个表同步到StarRocks中的一个表，
同步的时候需要加一个字段区分数据源是哪个Mysql数据库

**Comment by baisui1981** [comment]
收到，会在后续版本中完善该功能

**Comment by baisui1981** [comment]
需求不明
> 需要加一个字段区分数据源是哪个Mysql数据库 
的生成规则是啥？
