### ISSUE TITLE
[feat]需要定义数据同步可自定义表列映射

### ISSUE THREAD

**Issue by baisui1981** [datavane/tis#225]
设置批量同步通道源表->目标表的列是强一致（数量，名称是保持强一致的）,但是一般场景下，用户希望自定义列映射关系，例如：
1. 在目标表上添加额外列
2. 将源表中的列设置别名到目标表上

功能实现可以利用DataX transform机制来实现 https://github.com/alibaba/DataX/blob/master/transformer/doc/transformer.md

![原表选择](https://github.com/qlangtech/tis/assets/21274618/e869a3a5-7b89-4868-9873-602f2c58b2c9)
[编辑](https://www.processon.com/diagraming/645e0fa4f4065d11d7e32a5b)

**Comment by piaoyaoi** [comment]
![image](https://github.com/datavane/tis/assets/38310230/c8861c1a-6f48-494c-a31c-840b354d2459)
还没有发布吗

**Comment by Tandoy** [comment]
希望自定义列映射关系，例如：

![微信截图_20240228100528](https://github.com/datavane/tis/assets/56899730/26797c7c-dc7e-4514-b37a-6feaba7f1873)

**Comment by baisui1981** [comment]
> 定义列映射关系，例如：

一般表字段名称，source端和sink 端保持一致的吧

**Comment by baisui1981** [comment]
> 希望自定义列映射关系，例如：
> 
> ![微信截图_20240228100528](https://private-user-images.githubusercontent.com/56899730/308392770-26797c7c-dc7e-4514-b37a-6feaba7f1873.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMDYxODgsIm5iZiI6MTcwOTEwNTg4OCwicGF0aCI6Ii81Njg5OTczMC8zMDgzOTI3NzAtMjY3OTdjN2MtZGM3ZS00NTE0LWIzN2EtNmZlYWJhN2YxODczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDA3MzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZDAxZWE3OGYyZmVhMjJiZjZiNGJjMDhhZjljNjQ2MDY4YmI3MDU3OTJlZmM5MjgyNWIyZjkyMWVkMjY5ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mpyyi9qJ2RW9GcAlv_kV0U0FhDirhdYMDRxRwHbn-vw)

一般表字段名称，source端和sink 端保持一致的吧

**Comment by baisui1981** [comment]
已经实现以下transformer算子：
|名称| 功能说明|
|-|-|
|Data Masking| 用于用户数据脱敏，例如，业务系统私密数据需要导入到数仓，如，用户名、密码之类数据需要进行脱敏处理。处理方法比较简单，字段内容进行遮照处理，例如：原用户名为‘王五’处理后为‘王*’|
|Concat Fields| 将原记录中的多个字段值，通过字符串连接的方式合并成一个记录值|
|JSON Splitter| 将原有记录中具有JSON Object格式的字段，拆分成多个新的字段|
|Copy Field| 将原有记录拷贝到|
|SubStr||
