### ISSUE TITLE
[bug]构建MySQL-CDC到ClickHouse， CSV解析主键ID有误

### ISSUE THREAD

**Issue by devttl** [datavane/tis#244]
解析有误日志里面不定时报错，查询ClickHouse数据库正常已经插入
![image](https://github.com/datavane/tis/assets/18227802/534d13ed-4f9a-4631-ae03-d0278f3433d5)
![image](https://github.com/datavane/tis/assets/18227802/a194b4da-8d63-4f2e-9b88-e768a9c469c0)

**Comment by baisui1981** [comment]
能否提供更详细的上下文信息，例如 mysql 建表ddl，另外再加一条 mysql `insert into` 语句，不然的话很难复现您提供的错误信息
