### ISSUE TITLE
sqlserver 表批量同步到doris  偶尔会报一些问题和错误

### ISSUE THREAD

**Issue by charlesqing** [datavane/tis#257]
08-23 15:10172.16.102.136 15:10:01.009 WARN  c.a.d.p.r.r.u.OriginalConfPretreatmentUtil-您的配置有误. 由于您读取数据库表采用了querySql的方式, 所以您不需要再配置 splitPk. 如果您不想看到这条提醒，请移除您源头表中配置中的 splitPk.

08-23 15:10 taskid:56,phase:[dump,join] faild,reason:status.runningStatus.isComplete():com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:sz_oa_ecology_to_doris_02,ERROR MSG:Process exited with an error: 1 (Exit value: 1)
08-23 15:10 full build job is failed
08-23 15:10 status.runningStatus.isComplete():com.qlangtech.tis.datax.DataXJobSingleProcessorException: dataX:sz_oa_ecology_to_doris_02,ERROR MSG:Process exited with an error: 1 (Exit value: 1)

**Comment by baisui1981** [comment]
日志上应该有详细的日志，可以把 日志文本下载到本地查看
![截屏2023-08-24 19 35 25](https://github.com/datavane/tis/assets/21274618/fa4fa5a2-074e-4e1d-9df7-41e119242650)

**Comment by baisui1981** [comment]
信息不全
