### ISSUE TITLE
不同用户下的相同名称表无法同步

### ISSUE THREAD

**Issue by jingjianqian** [datavane/tis#281]
同步授权表的时候：
Caused by: java.lang.IllegalStateException: duplicate table entities exist:DEMO_TEST_DG(SYNONYM,LSZW_TEMP_USER),DEMO_TEST_DG(TABLE,MS_AUTH)

另外是否不支持视图同步？
![image](https://github.com/datavane/tis/assets/16252523/fc6a5e5e-a60e-4647-962b-900f94090be6)

**Comment by jingjianqian** [comment]
好的，非常感谢，我试试

**Comment by baisui1981** [comment]
是的 ，这个错误说明，相同的表名在多个schema下有相同的表名，需要用户在设置数据源时，明确指定使用哪个schema。如下图
![截屏2023-11-05 16 13 22](https://github.com/datavane/tis/assets/21274618/f01ca260-caec-455c-bc4e-6d8d4fa985df)

需要视图导出，需要依赖 tis 的hive，在hive中构建视图宽表，然后到处到目标数据节点中
