### ISSUE TITLE
jdk11不支持吗？

### ISSUE THREAD

**Issue by djbcxc6881796** [datavane/tis#286]
Unrecognized VM option 'PrintGCDateStamps'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
![image](https://github.com/datavane/tis/assets/131864703/511cf2cd-3a1d-486f-bcc8-3aa231094df3)

**Comment by baisui1981** [comment]
可以自行对 ./bin/tis 启动脚本进行调整，可以将参数`-XX:+PrintGCDateStamps` 删除或者替换
```
JAVA_OPTS="-Xms2G -Xmx3G -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -XX:ParallelGCThreads=4 -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=utf-8 -Dtis.launch.port=$SERVER_PORT -DnotFetchFromCenterRepository=true -Ddata.dir=${TIS_TIP}/data -Dlog.dir=$LOG_FILE -Dweb.root.dir=${TIS_TIP}/  -Xrunjdwp:transport=dt_socket,address=50000,suspend=n,server=y"
```
