### ISSUE TITLE
TIS REST api 在哪里可以看

### ISSUE THREAD

**Issue by hufatong** [datavane/tis#287]
请问 TIS REST api 在哪里可以看

**Comment by baisui1981** [comment]
您需要哪些功能的 rest API？目前还没有生成标准的文档

**Comment by hufatong** [comment]
datax实例的作业调度，需要设置成自动调度的，要怎么调用api

**Comment by hufatong** [comment]
> datax实例的作业调度，需要设置成自动调度的，要怎么调用api

datax实例的作业调度，需要设置成自动调度的，要怎么调用api

**Comment by baisui1981** [comment]
> > datax实例的作业调度，需要设置成自动调度的，要怎么调用api
> 
> datax实例的作业调度，需要设置成自动调度的，要怎么调用api

可以使用以下命令触发：
curl  -H "Appname: mysql_aliyun_hive" -H "Referer:x" 'http://localhost:8080/tjs/coredefine/coredefine.ajax?action=datax_action&emethod=trigger_fullbuild_task'

只需要更改 header参数中的 `Appname` 为自己定义的数据通道名称即可

**Comment by hufatong** [comment]
> > > datax实例的作业调度，需要设置成自动调度的，要怎么调用api
> > 
> > 
> > datax实例的作业调度，需要设置成自动调度的，要怎么调用api
> 
> ### 可以使用以下命令触发：
> ```shell
> curl  -H "Appname: mysql_aliyun_hive" -H "Referer:x" 'http://localhost:8080/tjs/coredefine/coredefine.ajax?action=datax_action&emethod=trigger_fullbuild_task'
> ```
> 
> 只需要更改 header参数中的 `Appname` 为自己定义的数据通道名称即可

**Comment by hufatong** [comment]
> > > datax实例的作业调度，需要设置成自动调度的，要怎么调用api
> > 
> > 
> > datax实例的作业调度，需要设置成自动调度的，要怎么调用api
> 
> ### 可以使用以下命令触发：
> ```shell
> curl  -H "Appname: mysql_aliyun_hive" -H "Referer:x" 'http://localhost:8080/tjs/coredefine/coredefine.ajax?action=datax_action&emethod=trigger_fullbuild_task'
> ```
> 
> 只需要更改 header参数中的 `Appname` 为自己定义的数据通道名称即可

谢谢，可以正常调度了

**Comment by hufatong** [comment]
> > > datax实例的作业调度，需要设置成自动调度的，要怎么调用api
> > 
> > 
> > datax实例的作业调度，需要设置成自动调度的，要怎么调用api
> 
> ### 可以使用以下命令触发：
> ```shell
> curl  -H "Appname: mysql_aliyun_hive" -H "Referer:x" 'http://localhost:8080/tjs/coredefine/coredefine.ajax?action=datax_action&emethod=trigger_fullbuild_task'
> ```
> 
> 只需要更改 header参数中的 `Appname` 为自己定义的数据通道名称即可

谢谢，可以正常调度了
