### ISSUE TITLE
写入clickhosue时自动建表bug

### ISSUE THREAD

**Issue by Tandoy** [datavane/tis#292]
当切分主健选两个时，生成的DDL存在问题：order by 应该是用括号包含
![1](https://github.com/datavane/tis/assets/56899730/f95bff08-b5ef-43b3-9546-798b8f71f7a0)

![2](https://github.com/datavane/tis/assets/56899730/556ac6e0-e7af-4711-b8ba-ac0bc52a778b)

**Comment by Tandoy** [comment]
> 收到，暂时你可以通过手动编辑修改一下，右上角有保存按钮

好的，谢谢。有想法提交pr修复~

**Comment by baisui1981** [comment]
> 收到，暂时你可以通过手动编辑修改一下，右上角有保存按钮

就是这行逻辑修改一下就行 ：https://github.com/qlangtech/plugins/blob/ad516c39862a8da21f2c604441474a726e3f0d57/tis-datax/tis-datax-clickhouse-plugin/src/main/java/com/qlangtech/tis/plugin/datax/DataXClickhouseWriter.java#L97

**Comment by Tandoy** [comment]
> > 收到，暂时你可以通过手动编辑修改一下，右上角有保存按钮
> 
> 就是这行逻辑修改一下就行 ：https://github.com/qlangtech/plugins/blob/ad516c39862a8da21f2c604441474a726e3f0d57/tis-datax/tis-datax-clickhouse-plugin/src/main/java/com/qlangtech/tis/plugin/datax/DataXClickhouseWriter.java#L97

好的
