### ISSUE TITLE
终止任务bug

### ISSUE THREAD

**Issue by Tandoy** [datavane/tis#294]
1.SQL Server --> SQL Server 多张表同步，当终止第一个任务时，实例显示终止成功并且状态是失败。但是实际上第二个同步任务还在运行

![1](https://github.com/datavane/tis/assets/56899730/54f191ad-0636-4283-8388-de3a64b7900e)

![3](https://github.com/datavane/tis/assets/56899730/a613a464-1d27-438e-8fc2-5fe195dd9c18)

**Comment by baisui1981** [comment]
收到

**Comment by baisui1981** [comment]
可以正常终止
