### ISSUE TITLE
当表没有物理主键在reader批量设置过程没有有效提示信息

### ISSUE THREAD

**Issue by Tandoy** [datavane/tis#295]
Mysql  --> Mysql
如果同时选择多张表进行批量设置，如果源表没有主键，则主键构建失败，导致无法下一步。
建议：当源表没有主键时，随机选取字段当选主键进行切分

![1](https://github.com/datavane/tis/assets/56899730/38a8be2a-d384-47b9-b58f-fa7d0d294faa)

![2](https://github.com/datavane/tis/assets/56899730/5d15cfef-bc72-4778-813f-457f9e6245d9)

**Comment by baisui1981** [comment]
目前没有主键情况下，点击`下一步` ，报告什么错误信息？可以第一时间定位到，由于表没有物理主键的原因不？

**Comment by Tandoy** [comment]
> 目前没有主键情况下，点击`下一步` ，报告什么错误信息？可以第一时间定位到，由于表没有物理主键的原因不？

没有报错日志，只是点击下一步没有反应，不会跳到writer设置页面。然后每点击一次下一步就会出现下面截图中的一行日志

![微信截图_20231218145232](https://github.com/datavane/tis/assets/56899730/4c91d804-f19d-40f5-ba8c-0be140a1096f)

**Comment by baisui1981** [comment]
> > 目前没有主键情况下，点击`下一步` ，报告什么错误信息？可以第一时间定位到，由于表没有物理主键的原因不？
> 
> 没有报错日志，只是点击下一步没有反应，不会跳到writer设置页面，只有当每个表都设置了切分主键后才能到writer设置界面。然后每点击一次下一步就会出现下面截图中的一行日志
> 
> ![微信截图_20231218145232](https://private-user-images.githubusercontent.com/56899730/291175062-4c91d804-f19d-40f5-ba8c-0be140a1096f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODU5MTAsIm5iZiI6MTcwMjg4NTYxMCwicGF0aCI6Ii81Njg5OTczMC8yOTExNzUwNjItNGM5MWQ4MDQtZjE5ZC00MGY1LWJhOGMtMGJlMTQwYTEwOTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA3NDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkYzBkNDM1M2IxYTg5MzBiMTU5OTNkOGE5MzZjNjZjOTkyMTllYTZkNTNmZDYyMTVkZjUyOTcxNmY2MTgzNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IjBlnJv3t0L4xeIq_jCozqM-Xq3UI2vmXBopzK3XJaI)

ok, 了解了，需要添加明确的不能进入下一步的错误原因
