### ISSUE TITLE
实例并发运行bug

### ISSUE THREAD

**Issue by Tandoy** [datavane/tis#297]
测试中发现：如果存在一个实例任务数据同步在运行中，启动一个新实例构建，任务显示执行中但实际没有执行

![微信截图_20231219155713](https://github.com/datavane/tis/assets/56899730/4e3876c0-0064-412c-9a1d-28834b5fcc54)

![微信截图_20231219155958](https://github.com/datavane/tis/assets/56899730/bddb7bc1-8939-4099-9cb1-c03d22fd22ae)

**Comment by baisui1981** [comment]
是的，由于单机版中资源有限，需要之前的任务执行成功之后 ，才会线性触发下一个管道任务的。目前正在实现 https://github.com/datavane/tis/issues/157 ，基于powerjob的分布式任务执行，等到发布后可以在分布式环境中并发执行管道任务
