### ISSUE TITLE
flink按重启策略重新拉起连接后，binlog的位点同步不正确

### ISSUE THREAD

**Issue by zyczw** [datavane/tis#299]
flink同步失败之后 ，binlog的位点 已经 移动过去了，等重启之后 没有去重新消费 之前失败的位点的消息
配置：
![image](https://github.com/datavane/tis/assets/69512786/3f97e5e6-6353-48bc-90ff-6e5ab6897bc7)

**Comment by baisui1981** [comment]
和https://github.com/datavane/tis/issues/274 重复
