### ISSUE TITLE
【建议】增加任务实例和数据源复制功能

### ISSUE THREAD

**Issue by MYiYang** [datavane/tis#303]
- **数据源创建**
    在多源场景下，现阶段需要手动一个一个重新添加新源信息，希望增加复制功能可以在已新建源的基础上直接复制修改
- **任务实例** 
    在多任务重复实例下，手动一个一个创建极为浪费时间，希望通过实例复制克隆的方式进行部分修改以实现任务实例的创建

**Comment by baisui1981** [comment]
good idea

**Comment by baisui1981** [comment]
## 数据同步管道克隆
![截屏2024-07-20 22 57 35](https://github.com/user-attachments/assets/03426d68-2c57-493e-8113-47353efdcf18)
## 数据源克隆
![截屏2024-07-20 22 59 42](https://github.com/user-attachments/assets/f14dc6bd-da85-45b6-8330-fcfb1a00b143)

**Comment by baisui1981** [comment]
已经实现了
