### ISSUE TITLE
【Bug】java.lang.ClassNotFoundException: com.dtstack.chunjun.connector.doris.sink.DorisHttpOutputFormat

### ISSUE THREAD

**Issue by Level1Accelerator** [datavane/tis#304]
版本：mysql5.7 doris 1.2.7 flink1.15.4
步骤：配置实时同步mysql cdc写入到doris,chunjun sink已经添加
错误：找不到chunjun sink doris的类

**Comment by baisui1981** [comment]
需要用TIS定制flink，你使用flink 官方发布的1.15.4应该是无法正常启动的

TIS定制Flink 下载及安装说明：https://tis.pub/docs/install/flink-cluster/standalone

**Comment by Level1Accelerator** [comment]
> 需要用TIS定制flink，你使用flink 官方发布的1.15.4应该是无法正常启动的
> 
> TIS定制Flink 下载及安装说明：https://tis.pub/docs/install/flink-cluster/standalone

感谢回复，我看了适配的chunjun，支持的flink版本是1.12
