### ISSUE TITLE
【UI】Table DDL Script名称过长问题

### ISSUE THREAD

**Issue by MYiYang** [datavane/tis#305]
![0ac12af43cd87e592846417f169b43c](https://github.com/datavane/tis/assets/27657784/5c4509df-9e90-4e2a-96cb-3bfbb0351b5f)

因为表名称过长导致后面的被遮挡

**Comment by baisui1981** [comment]
嗯，由于表名过长，届时会采用名称截断的方式，保证可视化效果

**Comment by baisui1981** [comment]
已经修改了
