### ISSUE TITLE
k8s datax 分布式

### ISSUE THREAD

**Issue by betranded** [datavane/tis#315]
![image](https://github.com/datavane/tis/assets/169508712/51465da7-7703-4606-82cd-de97513f797d)
重启pod失败

**Comment by betranded** [comment]
现在准备使用4.0.0-rc1 这个版本，因单机版有任务数据量限制。发现更新了。就来测试部署powerjob-server但是提示没有权限pull镜像

**Comment by betranded** [comment]
还有问题，宿主机应用名称和密码，这个没有理解，是k8s的account还是 系统的账户？

**Comment by baisui1981** [comment]
看一下 pod里面是不是有啥异常？ kubectl logs podname

**Comment by betranded** [comment]
第一次是成功了。然后看日志restart 就失败了

**Comment by betranded** [comment]
tis-datax-executor:4.0.0-rc1 不能pull下来
![image](https://github.com/datavane/tis/assets/169508712/378054a2-f62b-4ccb-a90f-9a542c935775)

**Comment by betranded** [comment]
这个是powerjo-worker日志。powerjob-server是running的

**Comment by baisui1981** [comment]
再试一下： docker pull registry.cn-hangzhou.aliyuncs.com/tis/tis-datax-executor:4.0.0-rc1
之前发布的时候没有把 `-rc1` 后缀带上，现在应该ok了

**Comment by betranded** [comment]
刚才拉取下来了。多谢指导

**Comment by betranded** [comment]
![image](https://github.com/datavane/tis/assets/169508712/224d8bb8-0e97-4706-822b-1854586d4465)
![image](https://github.com/datavane/tis/assets/169508712/76d6060d-6098-4846-93af-10036479d05d)
flink 和powerjob pod 现在都是运行的，但是页面上datax执行器，一直加载不出来。flink也没有
![image](https://github.com/datavane/tis/assets/169508712/b74a2f96-c36d-494b-adbd-5a96a262cf81)

**Comment by betranded** [comment]
一直加载
![image](https://github.com/datavane/tis/assets/169508712/f489aae5-d83b-4bd9-94e6-3d9b946f1e5c)

**Comment by betranded** [comment]
svc 
![image](https://github.com/datavane/tis/assets/169508712/8a269cbe-fc23-49ad-ae0b-b148123a5f8b)
flink 是可以访问的

**Comment by baisui1981** [comment]
使用kubectl 将已经创建powerjob 资源都删除掉，然后点击`Flink kubernate Session添加` 按钮，再创建一遍。
之前的流程由于 docker image path 没有拿到卡在最后一步没有把 创建的集群拓扑信息写入到TIS相关配置中

**Comment by baisui1981** [comment]
方便的话加我一下微信：16660356

**Comment by betranded** [comment]
加您了

**Comment by baisui1981** [comment]
已经顺利完成测试
