### ISSUE TITLE
基于docker-compose安装TIS后，配置增量通道成功执行任务时，flink job提示Could not acquire the minimum required resources 

### ISSUE THREAD

**Issue by jiewenk** [datavane/tis#331]
我在windows上使用VMWare虚拟机通过docker-compose方式安装TIS，使用了文档中的docker-compose.yaml配置文件，只改动了yaml文件中顶部的version版本，正常启动后，创建了批量处理任务，从MySQL到ES，这一步成功同步，然后创建了增量通道，通过Flink，这一步也成功了，但是创建的增量任务状态一直是CREATED，查看日志也一直在报Could not acquire the minimum required resources ，请问这应该怎么解决呢？我看flink的web控制台中JobManager的JVM只有1G，但我将docker-compose文件中的flink对应的mem值修改到4g重启后查看对应的JVM大小还是1G，这里就有点没明白了。请指教

**Comment by baisui1981** [comment]
请确认两点：
1. 运行增量通道之前，是否已经运行了其他的同步任务？
2. docker部署所在节点是否有足够的内存和CPU资源？

**Comment by jiewenk** [comment]
![image](https://github.com/datavane/tis/assets/106599923/ba71d306-3125-4c27-bf5c-3fc487d356d2)

目前虚拟机的内存大小是足够的，虚拟机的cpu配置的是4C
![image](https://github.com/datavane/tis/assets/106599923/e257fa0e-2172-4408-b373-326402309cf3)

**Comment by baisui1981** [comment]
能否看一下 Could not acquire the minimum required resources 的详细的异常栈？

**Comment by jiewenk** [comment]
堆栈信息暂时给不出，下午的时候给您回复
然后，并行度确实重新设置了
![image](https://github.com/datavane/tis/assets/106599923/24c08920-aeae-4f3b-ba2c-7c8566c8d6d3)

**Comment by baisui1981** [comment]
我就知道你肯定设置了并行度了，先改成1，docker-compose 运行的flink只是作为示例用，flink-config配置文件中的slot写死是 1，当并行度大于1 时候，确实是会报资源不足的异常的。

如要使用并行度大于1的场景，请使用TIS提供的其他flink部署方案

**Comment by jiewenk** [comment]
好的，感谢
