### ISSUE TITLE
mongodb同步时希望可以增加动态的参数，例如当天时间或者支持自定义

### ISSUE THREAD

**Issue by kevinlin299** [datavane/tis#335]
![image](https://github.com/datavane/tis/assets/40079776/30d0cc9f-ab4e-441c-a0f4-eec8526a4c78)
添加了query参数之后不知道其实现原理是什么，希望也可以输出到日志或者输出参数配置。
tis是一个超好用的ETL工具，感谢开源！！！

**Comment by baisui1981** [comment]
https://github.com/qlangtech/plugins/blob/9a2775f6204ca42db2a1ae36b6a3c0697d4eb3eb/tis-datax/tis-datax-mongodb-plugin/src/main/java/com/qlangtech/tis/plugin/datax/mongo/reader/ReaderFilterNormalQuery.java#L27

在页面上指定的`normalQuery`类型的过滤条件就是通过以下`createFilter()`代码片段生效的
``` java
    @FormField(ordinal = 1, type = FormFieldType.TEXTAREA, validate = {Validator.require})
    public String query;

    @Override
    public Document createFilter() {
        Document fitler = Document.parse(query);
        return fitler;
    }
```
