### ISSUE TITLE
MySQL版本:'10.5.21 使用哪种插件安装

### ISSUE THREAD

**Issue by 472893615** [datavane/tis#337]
请确认连接参数是否正确:实际MySQL版本:'10.5.21-MariaDB-1:10.5.21+maria-ubu2004'与插件:'MySQL-V5'支持的版本不一致
请确认连接参数是否正确:实际MySQL版本:'10.5.21-MariaDB-1:10.5.21+maria-ubu2004'与插件:'MySQL-V8'支持的版本不一致
相关issue： https://github.com/datavane/tis/issues/307

**Comment by baisui1981** [comment]
目前`MySQL-V8` 使用的是以下mysql JDBC驱动依赖，您在使用过程中会报什么错误异常，请告知
```xml
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.31</version>
        </dependency>
```
reference from：https://github.com/qlangtech/plugins/blob/9a2775f6204ca42db2a1ae36b6a3c0697d4eb3eb/tis-datax/tis-ds-mysql-v8-plugin/pom.xml#L40C8-L44C22

**Comment by baisui1981** [comment]
添加MariaDB端类型支持
![截屏2024-07-20 22 48 03](https://github.com/user-attachments/assets/96e158f6-fa2e-4fd6-bd03-0d871ade680f)

**Comment by 472893615** [comment]
> 添加MariaDB端类型支持 ![截屏2024-07-20 22 48 03](https://private-user-images.githubusercontent.com/21274618/350701244-96e158f6-fa2e-4fd6-bd03-0d871ade680f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTkxMTIsIm5iZiI6MTcyMTYxODgxMiwicGF0aCI6Ii8yMTI3NDYxOC8zNTA3MDEyNDQtOTZlMTU4ZjYtZmEyZS00ZmQ2LWJkMDMtMGQ4NzFhZGU2ODBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAzMjY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYWJmNGJiMWFhNzljNGIyZTkyYWQwMWY4MDk5NjRjODUyOTUyOTA2ZWUzZjE4N2JiNmU5OGY4MmNiYWNkMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hK584sWKEurpXdwRcayu5q2waG8pMumPwR3hSfPwi6Q)

我在插件管理面没有找到MariaDB端类型支持

**Comment by baisui1981** [comment]
届时 4.0.1 版本发布， 会添加

**Comment by 472893615** [comment]
> 届时 4.0.1 版本发布， 会添加

大约什么时间会更新

**Comment by baisui1981** [comment]
> > 届时 4.0.1 版本发布， 会添加
> 
> 大约什么时间会更新
关注 https://github.com/datavane/tis/milestone/6 即可
