### ISSUE TITLE
tis 定义好的批处理任务如何与现有的调度系统集成

### ISSUE THREAD

**Issue by lordk911** [datavane/tis#339]
https://github.com/datavane/tis/issues/287  这里提供了触发任务启动的API
但是如何监控任务是否正常结束呢？
一般场景可能是，数据同步过来之后要做下一步的加工，需要将批量任务集成到工作流中。

**Comment by baisui1981** [comment]
之前在ds中做了一个与tis集成的插件，可以参考一下 https://github.com/apache/dolphinscheduler/issues/5992
