### ISSUE TITLE
tis 4.0 不支持用UserPass的方式访问hdfs

### ISSUE THREAD

**Issue by ftpxzxh** [datavane/tis#341]
![26b0e7fb7c8c5721935fa022a4ee47a](https://github.com/user-attachments/assets/1995c749-b974-4ed5-b7d7-2a4a147b4d89)
4.0版本不支持账号密码的方式访问hdfs，希望可以支持一下，谢谢

**Comment by baisui1981** [comment]
能提供 对应的 一段用 用户名密码 访问hdfs 的 java示例代码？

**Comment by ftpxzxh** [comment]
您的邮件我已收到，我会尽快阅读的，谢谢！

**Comment by ftpxzxh** [comment]
![微信图片_20240725175843](https://github.com/user-attachments/assets/e0e08dfa-ca36-4632-bd6a-1dd8f7839a52)
配置了hadoop用户也不行
![微信图片_20240725175919](https://github.com/user-attachments/assets/6368a9ab-309e-4c53-8578-2cbc5539f6c2)

**Comment by ftpxzxh** [comment]
用hadoop用户启动tis是可以成功的
