### ISSUE TITLE
TIS的datax不能同步注释和视图

### ISSUE THREAD

**Issue by hapeacock** [datavane/tis#350]
大哥，我ORACLE数据库入doris，经过测试，
datax不能同步注释，视图也查找不到。不能同步
希望加上去，或有什么办法可以搞一下哇

**Comment by baisui1981** [comment]
> 大哥，我ORACLE数据库入doris，经过测试， datax不能同步注释，视图也查找不到。不能同步 希望加上去，或有什么办法可以搞一下哇

1. 数据库`视图`确实是不能同步的
2. 表注释、列注释可以加，后续版本会提供

**Comment by hapeacock** [comment]
我另外个群说视图可以，注释不行。。。
![image](https://github.com/user-attachments/assets/c34ece7f-2e59-41cb-9774-13b1e008b62a)
老根啊。1981的
视图也相当于一个表吧，可能是tis里面的jdbc读取不到。，之前有个dataease软件也是读取不到视图，后面也可以了
