### ISSUE TITLE
创建了实例，但是实例列表里面没有

### ISSUE THREAD

**Issue by bibichuan** [datavane/tis#357]
我创建了一个实例，已经 创建成功了，但是查看实例列表的时候，却没有。
![691212976fce4c62b79ee5f3546bc10c](https://github.com/user-attachments/assets/fbb7e133-eb11-43d6-9761-1d0d87c54036)
重新创建的时候，发现已经存在了 
![图片](https://github.com/user-attachments/assets/d0f72b15-a4be-4470-a58b-dbd330a54ad5)

**Comment by baisui1981** [comment]
有微信不？
