### ISSUE TITLE
服务端获取不到该Job状态信息，可能是因为Flink-Cluster重启导致，请手动

### ISSUE THREAD

**Issue by bibichuan** [datavane/tis#358]
我已经成功创建了一个 flink-cdc 实例，可以实现数据实时同步，但是当我创建第二个同步实例的时候，总是不成功，尝试了很多次，都不行，报错：服务端获取不到该Job状态信息，可能是因为Flink-Cluster重启导致，请手动
![图片](https://github.com/user-attachments/assets/ec4c074d-648c-42ee-9fbd-5a8e259912ce)
我多次删除增量实例，重新创建，一次也不成功。

**Comment by baisui1981** [comment]
应该是solt已经耗尽，请参考：https://tis.pub/docs/install/flink-cluster/standalone#1-could-not-acquire-the-minimum-required-resources
