### ISSUE TITLE
Make flink-cdc for mysql source connector support tableName matcher with regex pattern

### ISSUE THREAD

**Issue by wzc789376152** [datavane/tis#360]
假如有表table_01,table_02,table_03设置了增量同步，当id达到阈值，会自动新建表table_04。table_04没有增量自动同步。
版本：4.0.0

**Comment by baisui1981** [comment]
目前在增量执行启动过程中如果是分表，匹配规则是分表全表名完全一致匹配，所以运行期有新增分表不会自动监听需要，增量任务停机重启的方式才会生效。
这块执行逻辑应该是可以改的，改成正则式匹配逻辑。

**Comment by wzc789376152** [comment]
怎么改逻辑？改源代码么？
