### ISSUE TITLE
分表识别自定义规则怎么设置？

### ISSUE THREAD

**Issue by wzc789376152** [datavane/tis#361]
表分区策略设置为on，分表识别规则不管怎么设置都是默认的。不起作用。

**Comment by baisui1981** [comment]
能否加详细说明一下？或者加微信 16660356

**Comment by wzc789376152** [comment]
涉及的表如下
CREATE TABLE `db_code_bind_log_2024_5` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='码日志表';

CREATE TABLE `db_code_bind_log_2024_6` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='码日志表';

CREATE TABLE `db_code_bind_log_2024_7` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='码日志表';

CREATE TABLE `db_code_bind_log_2024_8` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='码日志表';

CREATE TABLE `db_code_bind_log_2024_9` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='码日志表';

另一种规则表

CREATE TABLE `db_code_point_100` (
  `id` bigint NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='码表';

CREATE TABLE `db_code_point_101` (
  `id` bigint NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='码表';

CREATE TABLE `db_code_point_102` (
  `id` bigint NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='码表';

**Comment by wzc789376152** [comment]
问题描述，在开启分表规则策略时 db_code_bind_log 相关的几个表，只会满足(\S+)_(\d+)匹配规则，合并成db_code_bind_log_2024，无论怎么设置都是无效的。db_code_point 表则会按照规则合并，但是设置不属于它的规则，也通向合并db_code_point。
<img width="998" alt="微信图片_20240920125048" src="https://github.com/user-attachments/assets/01ed9d15-f3f8-4b36-9c28-4fb36d5ab1d9">
<img width="338" alt="微信图片_20240920125154" src="https://github.com/user-attachments/assets/1aac2024-e250-4bad-b390-80de31577c32">
<img width="221" alt="微信图片_20240920125215" src="https://github.com/user-attachments/assets/fd4b3456-b17c-4d6b-b2f1-80e67073f3aa">

**Comment by baisui1981** [comment]
查看了一下代码，确实如您所说使用默认值在进行匹配，这个已经修复了。
另外，正对您提供的两种表的样式，可以使用正则式：`(\S+?)_([\d_]+)` 进行匹配，可识别成以下两个逻辑表名：
1. db_code_bind_log
2. db_code_point
