### ISSUE TITLE
TIS构建tis-transformer编译报错，下载不了插件，该如何解决呢？

### ISSUE THREAD

**Issue by wang550301463** [datavane/tis#367]
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/2adf530d-4d4e-4061-b778-09eed0fd29a2">

``` shell
[ERROR] Failed to execute goal on project tis-transformer: Could not resolve dependencies for project com.qlangtech.tis.plugins:tis-transformer:tpi:4.0.1: com.qlangtech.tis.plugins:tis-datax-common-plugin:jar:4.0.0 was not found in http://mvn-repo.oss-cn-hangzhou.aliyuncs.com/release/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of tis-repo-releases has elapsed or updates are forced -> [Help 1]
```

**Comment by baisui1981** [comment]
master 分支是开发分支，可以先用 release 打了tag的 来编译

**Comment by wang550301463** [comment]
<img width="2238" alt="image" src="https://github.com/user-attachments/assets/df89e0f7-b7b9-411d-809d-73557f49215c">
你好，我使用了v4.0.0版本install的时候遇到config未实现方法 ，对应的tis-config版本如下 
    <dependency>
            <groupId>com.qlangtech.tis</groupId>
            <artifactId>tis-config</artifactId>
            <version>1.0.1</version>
        </dependency>

**Comment by wang550301463** [comment]
<img width="1760" alt="image" src="https://github.com/user-attachments/assets/94dab714-6964-49d8-996e-43c94262ab61">
使用了v4.0.0版本，上面的我自己加了一下，但是后面又遇到了tis-common-dao: Compilation failure。看pom里面引用的是Spring3.0.6。这个该怎么解决呢

**Comment by wang550301463** [comment]
<img width="2534" alt="image" src="https://github.com/user-attachments/assets/d667481d-24a7-4fa4-bca4-4d760d6e86c5">
用了4.0也找不到包

**Comment by baisui1981** [comment]
能否提供一下执行的mvn 命令
