### ISSUE TITLE
定时同步失败，且没有日志输出

### ISSUE THREAD

**Issue by zzxVv** [datavane/tis#368]
在进行sqlserver同步至doris的datax定时同步任务时，时间跨度长、准点进行的同步任务会失败，且powerjob节点参数显示为tisWorkflowChannel":false,"dataxName":"wmsWebHot_sync_doris，任务结果为com.qlangtech.tis.lang.TisException: maxRetry:1,url:“172.16.201.5:8080/tjs/config/config.ajax?action=fullbuild_workflow_action&event_submit_do_initialize_trigger_task=true”。
![333](https://github.com/user-attachments/assets/d3e1a2c7-51e5-4dc7-8d6b-29e2db092af8)

**Comment by baisui1981** [comment]
是不是TIS 没有部署在和powerjob 同一个k8s集群中？导致 
`“172.16.201.5:8080/tjs/config/config.ajax?action=fullbuild_workflow_action&event_submit_do_initialize_trigger_task=true”`
无法访问。

**Comment by zzxVv** [comment]
> 是不是TIS 没有部署在和powerjob 同一个k8s集群中？导致 无法访问。`“172.16.201.5:8080/tjs/config/config.ajax?action=fullbuild_workflow_action&event_submit_do_initialize_trigger_task=true”`

是的，TIS为本地单机docker部署，powerjob部署在单独的k8s集群中。但也不是一直不能访问，例如作业间隔设置为每两分钟或者五分钟一次可以正常运行。

**Comment by baisui1981** [comment]
> > 是不是TIS 没有部署在和powerjob 同一个k8s集群中？导致 无法访问。`“172.16.201.5:8080/tjs/config/config.ajax?action=fullbuild_workflow_action&event_submit_do_initialize_trigger_task=true”`
> 
> 是的，TIS为本地单机docker部署，powerjob部署在单独的k8s集群中。但也不是一直不能访问，例如作业间隔设置为每两分钟或者五分钟一次可以正常运行。

把tis 和powerjob 部署在同一个k8s 集群里，应该就没有问题
