### ISSUE TITLE
flink宕机

### ISSUE THREAD

**Issue by shizenghua** [datavane/tis#382]
flink运行几个小时后，web页面打不开。但是容器终端还能进入。
日志里无报错。
容器终端查看ps进程已经没有flink了。

**Comment by baisui1981** [comment]
背景 介绍一下，是用啥方式启动的？standalone，docker， k8s？ 是否有查看系统日志(vi /var/log/messages)？
如果是k8s的话 ，是否可以为pod 扩大内存规格 ？

**Comment by shizenghua** [comment]
应该就是内存的问题。
