### ISSUE TITLE
连接sqlserver数据库时名称不支持中文

### ISSUE THREAD

**Issue by bibichuan** [datavane/tis#387]
在添加数据源的时候，数据库名称不能是中文，也不能是大写开头

**Comment by bibichuan** [comment]
sqlserver数据库

**Comment by bibichuan** [comment]
![图片](https://github.com/user-attachments/assets/2c26e471-06ca-4dee-bab7-aa9df763324f)

**Comment by baisui1981** [comment]
收到，会尽快修改
