### ISSUE TITLE
sqlserver数据库连接问题，TSL版本问题

### ISSUE THREAD

**Issue by lfandrh** [datavane/tis#388]
### 用Docker-Compose部署的TIS 4.0.1版本，连接低版本的sqlserver数据库报错，用Nacivate和DBeaver数据库连接工具可以正常连接，报错信息如下：
```
请确认连接参数是否正确:com.microsoft.sqlserver.jdbc.SQLServerException: "encrypt" property is set to "false" and "trustServerCertificate" property is set to "false" but the driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption: Error: The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]. ClientConnectionId:2e54a58f-29e9-4862-a2f8-ee43a917fe62
```
尝试修改docker容器中java的配置文件

> /opt/java/openjdk/conf/security/java.secutiry

```
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA, ...
```
修改为
```
jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, ...
```
重启容器，发现配置文件的修改被保留，但是系统仍旧报错

**Comment by baisui1981** [comment]
已经在tis启动的脚本中添加了 `-Djdk.tls.client.protocols=TLSv1.2` jvm参数。

可以自己在 tis-uber/bin/tis 启动文件中加一下 `-Djdk.tls.client.protocols=TLSv1.2` 这个参数不，搞不定的话 加我微信：16660356

**Comment by lfandrh** [comment]
> 由于升级了jdk11导致的，已经在tis启动的脚本中添加了 `-Djdk.tls.client.protocols=TLSv1.2` jvm参数。
> 
> 可以自己在 tis-uber/bin/tis 启动文件中加一下 `-Djdk.tls.client.protocols=TLSv1.2` 这个参数不，搞不定的话 加我微信：16660356。
> 
> 如果急用的话可以先试试 4.0.0 版本

原本是用Docker-Compose部署的，尝试了一下没解决，现在改用单机部署了，修改了一下就可以了，感谢
