### ISSUE TITLE
内网环境如何离线安装插件

### ISSUE THREAD

**Issue by huansinho** [datavane/tis#396]
请问在公司内网服务器无法连接互联网的情况下如何安装插件？

错误信息：
加载远端仓库元数据异常: maxRetry:1,url:http://mirror.qlangtech.com/4.0.0/update-site/default.json?id=default&version=%3F

**Comment by baisui1981** [comment]
先在有网络环境的机器节点上 安装上所需要的插件 ，然后将所有tis-uber文件夹打一个包送到 内网环境中去就可以使用了

**Comment by huansinho** [comment]
容器内的这个目录需要同步复制吗? 

/app/tis/plugins

**Comment by huansinho** [comment]
docker挂载 /opt/data/libs/plugins/ 出来，然后把tpi都复制进去就好了。

**Comment by baisui1981** [comment]
> docker挂载 /opt/data/libs/plugins/ 出来，然后把tpi都复制进去就好了。

简单粗暴一点 ，可以把 `/opt/data`  作为同步的目标目录
