### ISSUE TITLE
mysql自动建表到doris，tinyint(4)类型会转为varchar(12)

### ISSUE THREAD

**Issue by gyp617280763** [datavane/tis#402]
mysql:
CREATE TABLE `hrpersonrank` (
  `RankID` bigint(20) NOT NULL COMMENT '主键ID',
  `RankName` varchar(256) NOT NULL COMMENT '级别名称',
  `Level` int(3) DEFAULT '1' COMMENT '级次',
  `Pid` bigint(20) DEFAULT '1' COMMENT '父级ID',
  `RankNO` varchar(50) DEFAULT '' COMMENT '职级编号',
  `Axis` varchar(256) DEFAULT '1' COMMENT '轴（1$2$3）',
  `Sort` int(4) DEFAULT '1' COMMENT '排序',
  `EnterID` bigint(20) DEFAULT NULL COMMENT '集团ID',
  `OwnerID` bigint(20) DEFAULT NULL COMMENT '操作人',
  `CreationDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `ModifiedDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `IsUse` bit(4) NOT NULL DEFAULT b'1' COMMENT '状态(1/0,使用/停用)',
  `bEnd` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否末级(1是,0否)',
  `Remarks` varchar(1024) DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`RankID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='职等设置'

doris:

CREATE TABLE `hrpersonrank` (
  `RankID` bigint(20) NOT NULL,
  `RankName` varchar(768) NULL,
  `Level` int(11) NULL,
  `Pid` bigint(20) NULL,
  `RankNO` varchar(150) NULL,
  `Axis` varchar(768) NULL,
  `Sort` int(11) NULL,
  `EnterID` bigint(20) NULL,
  `OwnerID` bigint(20) NULL,
  `CreationDate` datetime NULL,
  `ModifiedDate` datetime NULL,
  `IsUse` varchar(12) NULL,
  `bEnd` tinyint(4) NULL,
  `Remarks` varchar(3072) NULL
) ENGINE=OLAP
UNIQUE KEY(`RankID`)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(`RankID`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"is_being_synced" = "false",
"storage_format" = "V2",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false"
);

**Comment by baisui1981** [comment]
上面mysql表中没有发现哪个是 `tinyint(4)`类型的
